/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import connection.ConnectionFactory;
import dao.*;
import factory.DaoFactory;
import jakarta.persistence.EntityManager;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author Fecan
 */
public class Cadastrar extends javax.swing.JFrame {

    private Pessoa pessoa;
    private Cliente cliente;

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbName = new javax.swing.JLabel();
        LbEmail = new javax.swing.JLabel();
        TfName = new javax.swing.JTextField();
        TfEmail = new javax.swing.JTextField();
        LbTelefone = new javax.swing.JLabel();
        TfTelefone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BtVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbName.setText("Nome: *");

        LbEmail.setText("Email: *");

        TfName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TfName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TfNameFocusGained(evt);
            }
        });
        TfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNameActionPerformed(evt);
            }
        });

        TfEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TfEmailFocusGained(evt);
            }
        });
        TfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEmailActionPerformed(evt);
            }
        });

        LbTelefone.setText("Telefone:*");

        TfTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TfTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TfTelefoneFocusGained(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("* Campo Obrigatório.");

        BtVoltar.setText("Retornar");
        BtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfName)
                    .addComponent(TfEmail)
                    .addComponent(TfTelefone)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LbName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LbEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LbTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3))
                            .addComponent(BtVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(LbEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(BtVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNameActionPerformed

    private void TfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = TfName.getText();
        String email = TfEmail.getText();
        String telefone = TfTelefone.getText();

        if (nome.isBlank()) {
            LbName.setForeground(Color.RED);
        } else if (telefone.isBlank()) {
            LbTelefone.setForeground(Color.RED);
        } else if (email.isBlank()) {
            LbEmail.setForeground(Color.RED);
        } else {
            EntityManager em = null;
            try {
                em = new ConnectionFactory().getConnection();

                DaoFactory factory = new DaoFactory(em);
                PessoaDao pessoaDao = factory.getPessoaDao();
                ClienteDao clienteDao = factory.getClienteDao();
                pessoa = new Pessoa();
                pessoa.setEmail(email);
                pessoa.setNome(nome);
                pessoa.setTelefone(telefone);

                pessoaDao.salvarOuAtualizar(pessoa);

                pessoa = pessoaDao.buscarPorNome(nome);

                cliente = new Cliente();
                cliente.setIdPessoa(pessoa);
                clienteDao.salvarOuAtualizar(cliente);
                
                
                JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
                
            } catch (Exception ex) {
                System.out.println("Erro ao cadastrar: " + ex);
            } finally {
                if (em != null && em.isOpen()) {
                    em.close();
                }
            }
            TfName.setText("");
            TfTelefone.setText("");
            TfEmail.setText("");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void TfNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfNameFocusGained
        LbName.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_TfNameFocusGained

    private void TfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfEmailFocusGained
        LbEmail.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_TfEmailFocusGained

    private void TfTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfTelefoneFocusGained
        LbTelefone.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_TfTelefoneFocusGained

    private void BtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltarActionPerformed
        Acesso view = new Acesso();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtVoltar;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbName;
    private javax.swing.JLabel LbTelefone;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfName;
    private javax.swing.JTextField TfTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
